---
name: test

on:
  push:
    branches-ignore: [debian]
  pull_request:

jobs:
  test:
    name: Redmine ${{ matrix.redmine }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          - ruby: "3.1"
            redmine: "5.0.2"
          - ruby: "3.0"
            redmine: "5.0.2"
          - ruby: "2.7"
            redmine: "5.0.2"
      fail-fast: false

    env:
      BUNDLE_JOBS: 4
      BUNDLE_PATH: ${{ github.workspace }}/vendor/bundle
      BUNDLE_RETRY: 10
      BUNDLE_WITHOUT: development
      REDMINE_VERSION: ${{ matrix.redmine }}

    steps:
      - uses: actions/checkout@master

      - name: Setup database
        run: |
          sudo systemctl start postgresql
          sudo -u postgres createuser -s ${USER}

      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup ruby cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: v5-ruby-${{ matrix.ruby }}-redmine-${{ matrix.redmine }}-${{ hashFiles('Gemfile') }}

      - name: Setup Redmine ${{ matrix.redmine }}
        run: ./redmine update

      - name: Compile assets
        run: |
          yarn install
          yarn run build -- --mode production

      - name: Run plugin tests
        run: ./redmine exec bundle exec rspec spec/plugin --color

      - name: Run browser tests
        run: ./redmine exec bundle exec rspec spec/browser --color

  rubocop:
    runs-on: ubuntu-20.04

    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 10
      BUNDLE_WITHOUT: development

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: True

      - run: bundle exec rubocop --fail-level E --extra-details --display-time --color
